#!/bin/bash
echo sudo apt-get update
yes Y | sudo apt-get update
echo 
echo sudo apt-get upgrade
yes Y | sudo apt-get upgrade
echo 
echo sudo apt update
yes Y | sudo apt update
echo 
echo sudo apt full-upgrade
yes Y | sudo apt full-upgrade
echo 
echo sudo apt autoremove
yes Y | sudo apt autoremove
echo 
echo sudo apt-get dist-upgrade
yes Y | sudo apt-get dist-upgrade
echo 
echo Finihed
